---
# Tasks for launching ec2 instance

- ec2:
    key_name: JesusChrist
    region: us-east-1
    group: Lawson_AWS_Security_Grp
    image: ami-0057d8e6fb0692b80
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
    vpc_subnet_id: subnet-5ed82d15
    assign_public_ip: true
    count_tag:
      Name: docker
    exact_count: 1
    instance_tags:
      Name: docker
      Owner: Boma
